"""
Score LlamaGen candidate images with the PARM verifier (ORM mode).

For each prompt group, batches all N candidate images into a single forward pass
(same prompt → same input_ids → true batch). Uses max_new_tokens=1 since we only
need the first token's yes/no probability.

Input JSONL format (one row per candidate image):
  {"id": "p0001", "prompt": "A red cube ...", "image_path": "/path/to/img.png", "sample_index": 0}

Output JSONL: same rows + added fields:
  parm_yes_prob   float   probability of "yes"
  parm_selected   bool    whether model said "yes"
  parm_error      str     only present on failure

Usage:
  python adaptive_curriculum/parm_score_llamagen.py \
    --samples-jsonl outputs/llamagen_candidates/samples.jsonl \
    --output-jsonl  outputs/parm_scores/scores.jsonl \
    --parm-repo     /viscam/u/jj277/Image-Generation-CoT \
    --parm-ckpt     /viscam/u/jj277/Image-Generation-CoT/ckpts/Image-Generation-CoT/parm \
    --score-batch-size 4
"""
import argparse
import copy
import json
import sys
from collections import defaultdict
from pathlib import Path

import torch
from tqdm import tqdm


# ---------------------------------------------------------------------------
# Memory helpers
# ---------------------------------------------------------------------------

def _mem_gb() -> str:
    if not torch.cuda.is_available():
        return "N/A"
    alloc = torch.cuda.memory_allocated() / 1e9
    reserv = torch.cuda.memory_reserved() / 1e9
    return f"{alloc:.2f}GB alloc / {reserv:.2f}GB reserved"


def _print_mem(tag: str):
    print(f"[mem] {tag}: {_mem_gb()}", flush=True)


# ---------------------------------------------------------------------------
# Batched ORM scoring
# ---------------------------------------------------------------------------

def orm_batch(selector, prompt: str, image_paths: list, chunk_size: int = 4):
    """
    Score multiple candidate images for the same prompt in batched forward passes.

    All candidates share the same text question → input_ids are identical →
    true GPU batching. Uses max_new_tokens=1 (only first token needed).

    Returns list of (selected, yes_prob, norm_yes_prob) aligned with image_paths.
      yes_prob       — raw softmax prob of "yes" over full vocab (sparse, ~0–0.1)
      norm_yes_prob  — yes_prob / (yes_prob + no_prob)  (dense 0–1 reward signal)

    norm_yes_prob is the recommended reward for GRPO: it uses all the model's
    discriminative signal without being diluted by the ~150K other vocabulary tokens.
    Falls back to sequential on error.
    """
    from PIL import Image
    from llava.mm_utils import process_images, tokenizer_image_token
    from llava.constants import IMAGE_TOKEN_INDEX, DEFAULT_IMAGE_TOKEN
    from llava.conversation import conv_templates

    question = (
        f"{DEFAULT_IMAGE_TOKEN} This image is generated by a prompt: {prompt}. "
        f"Does this image accurately represent the prompt? "
        f"Please answer yes or no without explanation."
    )
    conv_template = "qwen_1_5"
    conv = copy.deepcopy(conv_templates[conv_template])
    conv.append_message(conv.roles[0], question)
    conv.append_message(conv.roles[1], None)
    prompt_question = conv.get_prompt()

    input_ids_single = tokenizer_image_token(
        prompt_question, selector.tokenizer, IMAGE_TOKEN_INDEX, return_tensors="pt"
    ).to(selector.device)

    yes_id = selector.tokenizer.convert_tokens_to_ids("yes")
    no_id  = selector.tokenizer.convert_tokens_to_ids("no")

    results = []
    for chunk_start in range(0, len(image_paths), chunk_size):
        chunk = image_paths[chunk_start: chunk_start + chunk_size]
        try:
            images = [Image.open(p) for p in chunk]
            image_tensors = process_images(images, selector.image_processor, selector.model.config)

            if isinstance(image_tensors, torch.Tensor):
                image_tensors = image_tensors.to(dtype=torch.float16, device=selector.device)
                img_list = [image_tensors[i] for i in range(len(images))]
            else:
                img_list = [t.to(dtype=torch.float16, device=selector.device) for t in image_tensors]

            image_sizes = [img.size for img in images]
            B = len(images)
            input_ids = input_ids_single.unsqueeze(0).repeat(B, 1)

            with torch.no_grad():
                cont = selector.model.generate(
                    input_ids,
                    images=img_list,
                    image_sizes=image_sizes,
                    do_sample=True,
                    temperature=1.0,
                    max_new_tokens=1,
                    return_dict_in_generate=True,
                    output_scores=True,
                )

            # scores[0]: (B, vocab_size) logits for first generated token
            first_scores = torch.nn.functional.softmax(cont.scores[0], dim=-1)
            yes_probs = first_scores[:, yes_id].tolist()
            no_probs  = first_scores[:, no_id].tolist()

            # LLaVA generate returns only the generated tokens (not input),
            # so cont.sequences has shape (B, n_new_tokens). With max_new_tokens=1
            # the generated token is always at index 0.
            generated_ids = cont.sequences[:, 0]
            responses = [
                selector.tokenizer.convert_ids_to_tokens([tok_id.item()])[0].lower()
                for tok_id in generated_ids
            ]

            for resp, yp, np_ in zip(responses, yes_probs, no_probs):
                norm_yp = yp / (yp + np_ + 1e-8)
                results.append((resp == "yes", yp, norm_yp))

        except Exception as e:
            print(f"  [warn] batch chunk failed ({e}), falling back to sequential", flush=True)
            for path in chunk:
                try:
                    sel, yp = selector.orm([prompt], path)
                    # sequential fallback: re-derive no_prob from the model's scores
                    # selector.orm only returns yes_prob; use 0.5 norm as fallback
                    results.append((sel, float(yp), 0.5))
                except Exception as e2:
                    print(f"  [warn] sequential fallback also failed for {path}: {e2}", flush=True)
                    results.append((False, 0.0, 0.0))

    return results


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def load_jsonl(path: str) -> list:
    rows = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.strip():
                rows.append(json.loads(line))
    return rows


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--samples-jsonl",   required=True,  help="Input JSONL of candidate images")
    p.add_argument("--output-jsonl",    required=True,  help="Output JSONL with PARM scores")
    p.add_argument("--parm-repo",       required=True,  help="Path to Image-Generation-CoT repo")
    p.add_argument("--parm-ckpt",       required=True,  help="Path to PARM checkpoint folder")
    p.add_argument("--device",          default="cuda")
    p.add_argument("--device-map",      default="single", choices=["single", "auto"],
                   help="'single' = GPU 0, 'auto' = multi-GPU via accelerate")
    p.add_argument("--score-batch-size", type=int, default=4,
                   help="Images per forward pass (all same prompt → true batching)")
    p.add_argument("--id-key",          default="id",
                   help="Field in input JSONL to use as prompt group key")
    args = p.parse_args()

    sys.path.insert(0, args.parm_repo)
    from selector import ImageSelector

    # Patch transformers to use eager attention when flash_attn is not installed.
    # selector.py does not pass attn_implementation, so transformers auto-detects
    # and raises if flash_attn is missing.
    try:
        import flash_attn  # noqa: F401
    except ImportError:
        import transformers.modeling_utils as _tmu
        @classmethod
        def _eager_attn_only(cls, config, *args, **kwargs):
            config._attn_implementation = "eager"
            config._attn_implementation_internal = "eager"
        _tmu.PreTrainedModel._check_and_enable_flash_attn_2 = _eager_attn_only

    # ---- Load PARM -----------------------------------------------------------
    print(f"[parm] Loading PARM from {args.parm_ckpt} ...", flush=True)
    _print_mem("before load")

    device_map = {"": 0} if args.device_map == "single" else "auto"
    selector = ImageSelector(
        pretrained=args.parm_ckpt,
        device=args.device,
        device_map=device_map,
    )

    _print_mem("after PARM load")
    total_params = sum(p.numel() for p in selector.model.parameters())
    print(f"[parm] Model params: {total_params / 1e9:.2f}B", flush=True)

    # ---- Load samples --------------------------------------------------------
    rows = load_jsonl(args.samples_jsonl)
    print(f"[parm] {len(rows)} candidates loaded from {args.samples_jsonl}", flush=True)

    # Group by prompt id so we can batch per-prompt
    groups: dict = defaultdict(list)
    for row in rows:
        groups[row[args.id_key]].append(row)

    print(f"[parm] {len(groups)} unique prompts, avg {len(rows)/len(groups):.1f} candidates each", flush=True)
    print(f"[parm] score-batch-size={args.score_batch_size}", flush=True)

    # ---- Score ---------------------------------------------------------------
    out_path = Path(args.output_jsonl)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    total_scored = 0
    with open(out_path, "w", encoding="utf-8") as fout:
        for pid, group in tqdm(groups.items(), desc="Scoring prompts"):
            prompt = group[0]["prompt"]
            image_paths = [r["image_path"] for r in group]

            # Validate paths before sending to GPU
            valid_mask = [Path(ip).exists() for ip in image_paths]
            if not all(valid_mask):
                missing = [ip for ip, v in zip(image_paths, valid_mask) if not v]
                print(f"  [warn] {len(missing)} images missing for prompt {pid}: {missing[:2]}", flush=True)

            scores = orm_batch(selector, prompt, image_paths, chunk_size=args.score_batch_size)

            for row, (image_path, (selected, yes_prob, norm_yes_prob)) in zip(
                group, zip(image_paths, scores)
            ):
                out_row = dict(row)
                out_row["parm_yes_prob"]      = yes_prob       # raw (sparse)
                out_row["parm_norm_yes_prob"] = norm_yes_prob  # yes/(yes+no) — use this for GRPO
                out_row["parm_selected"] = selected
                fout.write(json.dumps(out_row) + "\n")
                total_scored += 1

            fout.flush()

    _print_mem("after scoring")
    print(f"[parm] Done. {total_scored} images scored → {out_path}", flush=True)


if __name__ == "__main__":
    main()
